language: java
jdk:
  - oraclejdk8
# trusty version.
dist: trusty
sudo: required
env:
  - ES_VERSION=5.2.2 ES_DOWNLOAD_URL=https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-${ES_VERSION}.tar.gz
install:
  - wget ${ES_DOWNLOAD_URL}
  - tar -xzf elasticsearch-${ES_VERSION}.tar.gz
  - ./elasticsearch-${ES_VERSION}/bin/elasticsearch &
services:
  - mysql
  - redis
cache:
  directories:
    - $HOME/.m2
before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS spring_test;'
before_script:
  - echo "USE mysql;\nUPDATE user SET password=PASSWORD('pass') WHERE user='root';\nFLUSH PRIVILEGES;\n" | mysql -u root
  - sleep 10
script:
  # Make sure MySQL version.
  - mysql -h 127.0.0.1 -u root -p'pass' -D mysql -e "SELECT version()"
  # Make sure ES runs with wget command.
  - wget -q --waitretry=1 --retry-connrefused -T 10 -O - http://127.0.0.1:9200
  - mvn test
