spring:
    profiles:
        active: test
    devtools:
        restart:
            enabled: true
    datasource:
        url: jdbc:mysql://localhost:3306/spring_test
        name:
        username: root
        password: pass
        type: com.zaxxer.hikari.HikariDataSource
        hikari:
          maximum-pool-size: 3
          minimum-idle: 0
          idle-timeout: 10000
          max-lifetime: 30000
          read-only: false
    jpa:
        hibernate:
            ddl-auto: none
        database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
        show-sql: true
        format_sql: true
    thymeleaf:
        cache: false
    session:
        store-type: redis
    redis:
        host: ${REDIS_PORT_6379_TCP_ADDR:localhost}
        port: ${REDIS_PORT_6379_TCP_PORT:6379}

security:
    basic:
        enabled: false

server:
    port: 20983
    address: localhost
