spring:
    profiles:
        active: test
    devtools:
        restart:
            enabled: true
    datasource:
        url: jdbc:mysql://localhost:3306/spring_test
        name:
        username: root
        password: pass
        type: com.zaxxer.hikari.HikariDataSource
        hikari:
          maximum-pool-size: 3
          minimum-idle: 0
          idle-timeout: 10000
          max-lifetime: 30000
          read-only: false
    jpa:
        hibernate:
            ddl-auto: create-drop
        database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
        show-sql: true
        format_sql: true
    thymeleaf:
        cache: false
    session:
        store-type: redis
    redis:
        host: ${REDIS_PORT_6379_TCP_ADDR:localhost}
        port: ${REDIS_PORT_6379_TCP_PORT:6379}

security:
    basic:
        enabled: false

server:
    port: ${random.int[1024,65536]}
    address: localhost

hinagata:
    twitter4j:
        consumer_key: ${TWITTER_CONSUMER_KEY:You should export TWITTER_CONSUMER_KEY}
        consumer_secret: ${TWITTER_CONSUMER_SECRET:You should export TWITTER_CONSUMER_SECRET}
        access_token: ${TWITTER_ACCESS_TOKEN:You should export TWITTER_ACCESS_TOKEN}
        access_token_secret: ${TWITTER_ACCESS_TOKEN_SECRET:You should export TWITTER_ACCESS_TOKEN_SECRET}
