spring:
    profiles:
        active: dev
    devtools:
        restart:
            enabled: true
    datasource:
        url: jdbc:mysql://localhost:3306/spring_dev
        name:
        username: root
        password: pass
        type: com.zaxxer.hikari.HikariDataSource
        hikari:
          maximum-pool-size: 3
          minimum-idle: 0
          idle-timeout: 100000
          max-lifetime: 3000000
          read-only: false
    jpa:
        hibernate:
            ddl-auto: none
        database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
        show-sql: true
        format_sql: true
    thymeleaf:
        cache: false
    session:
        store-type: redis
    redis:
        host: ${REDIS_PORT_6379_TCP_ADDR:localhost}
        port: ${REDIS_PORT_6379_TCP_PORT:6379}

security:
    basic:
        enabled: false

server:
    port: 8080
    #session:
        #timeout: 5

hinagata:
    twitter4j:
        # Don't expose values in public. You should export those evn values.
        consumer_key: ${TWITTER_CONSUMER_KEY}
        consumer_secret: ${TWITTER_CONSUMER_SECRET}
        access_token: ${TWITTER_ACCESS_TOKEN}
        access_token_secret: ${TWITTER_ACCESS_TOKEN_SECRET}

