MAINTAINER forest6511
FROM elasticsearch:5.2.2

ENV ES_JAVA_OPTS="-Des.path.conf=/etc/elasticsearch"

# Japanese analyzer such as MeCab.
# http://www.atilika.com/ja/products/kuromoji.html
RUN elasticsearch-plugin install analysis-kuromoji
