FROM docker.elastic.co/logstash/logstash:5.2.2

# https://www.elastic.co/guide/en/logstash/current/docker.html

RUN rm -f /usr/share/logstash/pipeline/logstash.conf
ADD ./pipeline /usr/share/logstash/pipeline/

RUN rm -f /usr/share/logstash/config/logstash.yml
ADD ./config /usr/share/logstash/config/